# Generated by Django 4.2.4 on 2023-08-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='quote',
        ),
    ]
