# Generated by Django 4.2.4 on 2023-08-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_alter_author_fullname_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(),
        ),
    ]
